### ISSUE TITLE
Reconnect to IB in case of failed connection

### ISSUE THREAD

**Issue by Pl0414141** [wboayue/rust-ibapi#96]
To reproduce:

1. Open TWS
2. Connect via 'let mut client = Client::connect("127.0.0.1:7496", 100).unwrap();'
3. Close TWS

Expected result:

Script still alive and trying to reconnect.

Actual result:

Script terminated.

**Comment by richard-fairthorne** [comment]
Noticed this right away after installing. I was super happy at how fast and easy it was to connect, but I need to know if it fails.

**Comment by t00ts** [comment]
What's the status of this issue? Noticed @wboayue has a branch that may be related: `issue-96-reconnect`.

I'm not familiar with the project, but would consider chipping in if this is stalled. Handling connection failures seems like a crucial aspect of any system using this.

**Comment by wboayue** [comment]
@t00ts I have a branch open to fix a bug that occurs because I attempt to retry the connection. There are some cases where the library can successfully attempt a reconnection. However, in most cases, I think it's better for the library to properly propagate the network failures and let the application determine the course of action. What I'm working on fixing first are the cases where the library doesn't correctly propagate the network failures.
